CREATE TABLE IF NOT EXISTS images (
  url TEXT PRIMARY KEY,
  page_url TEXT NOT NULL,
  alt TEXT NOT NULL DEFAULT '',
  local_path TEXT NOT NULL DEFAULT '',
  width INTEGER NOT NULL DEFAULT 0,
  height INTEGER NOT NULL DEFAULT 0,
  format TEXT NOT NULL DEFAULT '',
  downloaded INTEGER NOT NULL DEFAULT 0
);
